### ISSUE TITLE
Esse módulo funciona no 1.9?

### ISSUE THREAD

**Issue by williannagano** [rafaelpatro/Quack_Jamef#1]
Testei aqui e não funcionou!

**Comment by rafaelpatro** [comment]
Sim, uso esse módulo em um Magento 1.9.3.4 e funciona normalmente.
Recompilou, após subir os arquivos?
Manda um print de como vc preencheu as configurações.

**Comment by williannagano** [comment]
' in C:\xampp\htdocs\irelax\app\Mage.php:580
Stack trace:
#0 C:\xampp\htdocs\irelax\app\code\community\Quack\Jamef\Model\Carrier\Shipping.php(96): Mage::exception('Mage_Core', 'Quack_Jamef_Mod...')
#1 C:\xampp\htdocs\irelax\app\code\core\Mage\Shipping\Model\Shipping.php(164): Quack_Jamef_Model_Carrier_Shipping->proccessAdditionalValidation(Object(Mage_Shipping_Model_Rate_Request))
#2 C:\xampp\htdocs\irelax\app\code\core\Mage\Shipping\Model\Shipping.php(129): Mage_Shipping_Model_Shipping->collectCarrierRates('quack_jamef', Object(Mage_Shipping_Model_Rate_Request))
#3 C:\xampp\htdocs\irelax\app\code\core\Mage\Sales\Model\Quote\Address.php(944): Mage_Shipping_Model_Shipping->collectRates(Object(Mage_Shipping_Model_Rate_Request))
#4 C:\xampp\htdocs\irelax\app\code\core\Mage\Sales\Model\Quote\Address.php(875): Mage_Sales_Model_Quote_Address->requestShippingRates()
#5 C:\xampp\htdocs\irelax\app\code\core\Mage\Sales\Model\Quote\Address\Total\Shipping.php(155): Mage_Sales_Model_Quote_Address->collectShippingRates()
#6 C:\xampp\htdocs\irelax\app\code\core\Mage\Sales\Model\Quote\Address.php(1013): Mage_Sales_Model_Quote_Address_Total_Shipping->collect(Object(Mage_Sales_Model_Quote_Address))
#7 C:\xampp\htdocs\irelax\app\code\core\Mage\Sales\Model\Quote.php(1331): Mage_Sales_Model_Quote_Address->collectTotals()
#8 C:\xampp\htdocs\irelax\app\code\core\Mage\Checkout\Model\Cart.php(461): Mage_Sales_Model_Quote->collectTotals()
#9 C:\xampp\htdocs\irelax\app\code\core\Mage\Checkout\controllers\CartController.php(161): Mage_Checkout_Model_Cart->save()
#10 C:\xampp\htdocs\irelax\app\code\core\Mage\Core\Controller\Varien\Action.php(418): Mage_Checkout_CartController->indexAction()
#11 C:\xampp\htdocs\irelax\app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#12 C:\xampp\htdocs\irelax\app\code\core\Mage\Core\Controller\Varien\Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 C:\xampp\htdocs\irelax\app\code\core\Mage\Core\Model\App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#14 C:\xampp\htdocs\irelax\app\Mage.php(684): Mage_Core_Model_App->run(Array)
#15 C:\xampp\htdocs\irelax\index.php(83): Mage::run('', 'store')
#16 {main}
2018-01-31T17:55:27+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Quack_Jamef_Model_Request_Time_Response Object
(
    [JAMW0520_04RESULT:Quack_Jamef_Model_Request_Time_Response:private] => Quack_Jamef_Model_Request_Time_Response_Result Object
        (
            [CDTMAX:Quack_Jamef_Model_Request_Time_Response_Result:private] => 
            [CDTMIN:Quack_Jamef_Model_Request_Time_Response_Result:private] => 
            [MSGERRO:Quack_Jamef_Model_Request_Time_Response_Result:private] => REGIAO DE ORIGEM [RUA ISOLDE TORQUATO TILLO, 46                               ]-[PR] NAO ENCONTRADA OU SEM FILIAL ASSOCIADA.;
        )

)

Ta me gerando esse log.

**Comment by williannagano** [comment]
![sem-titulo-1](https://user-images.githubusercontent.com/16063089/35639218-abc00b16-06a0-11e8-885b-4675df551f25.jpg)

**Comment by rafaelpatro** [comment]
Veja se seu CEP está corretamente configurado no Magento.

**Comment by rafaelpatro** [comment]
Ops, ignora oq eu disse. O CEP não é usado nesse módulo, mas sim o estado (UF). O problema está provavelmente relacionado a sigla da UF de origem. Veja se está configurada no Magento.

**Comment by williannagano** [comment]
Deu certo Rafael, eu que não coloquei a cidade certinho "configurações de entrega" e em filial de coleta eu mudei pra mesma cidade. Obrigado!

**Comment by williannagano** [comment]
Só uma sugestão pra mais pra  frente... O módulo poderia ter a opção de escolher entre Gramas e Quilos. Vlw!

**Comment by rafaelpatro** [comment]
Pois é, também pensei nessa opção de _gramas_ e _quilos_, mas ainda não pude implementar.
Se quiser enviar essa contribuição, será muito bem vinda.
