### ISSUE TITLE
Instalei o módulo com Magento 1.9.3.7 e php 7.1 e não funcionou

### ISSUE THREAD

**Issue by tomjmacedo** [rafaelpatro/Quack_Jamef#2]
Olá, instalei o módulo no magento 1.9.3.7 e php 7.1, porém não aparece as opções de cálculo de frete no frontend, porém no backend já configurei corretamente tanto as opções de Origem do Envio quanto as opções do módulo da Jamef.

**Comment by rafaelpatro** [comment]
Olá @tomjmacedo 
Pode mandar um print das configurações, pra eu ver se tem algo incomum?

**Comment by tomjmacedo** [comment]
Segue:
![2](https://user-images.githubusercontent.com/36165977/35817445-25958aae-0a7c-11e8-9275-c3aa0bd76c5f.png)
![1](https://user-images.githubusercontent.com/36165977/35817432-1d5c59e4-0a7c-11e8-864d-76581fd8ce01.png)

**Comment by rafaelpatro** [comment]
Parece Ok! Para analisarmos mais a fundo, precisamos dos logs do Magento.

1. Ativar os logs em _Sistema > Configuração > Desenvolvedor > Configurações de Log_
2. Monitorar o log via SSH: _tail -f /var/www/public_html/var/log/system.log_
3. Realizar uma cotação no frontend
4. Postar o resultado dos logs aqui

Enviar tb _exception.log_

**Comment by tomjmacedo** [comment]
system.log:

2018-02-05T17:13:21+00:00 DEBUG (7): Quack_Jamef_Model_Carrier_Shipping::proccessAdditionalValidation
2018-02-05T17:13:21+00:00 DEBUG (7): Quack_Jamef_Model_Request_Time::requestShippingTime
2018-02-05T17:13:22+00:00 DEBUG (7): REGIAO DE ORIGEM [VIT?RIA DA CONQUISTA                                        ]-[BA] NAO ENCONTRADA OU SEM FILIAL ASSOCIADA.;CLIENTE NAO INFORMADO.;



exception.log:

2018-02-05T17:22:55+00:00 ERR (3): 
Mage_Core_Exception: Quack_Jamef_Model_Request_Time_Response Object
(
    [JAMW0520_04RESULT:Quack_Jamef_Model_Request_Time_Response:private] => Quack_Jamef_Model_Request_Time_Response_Result Object
        (
            [CDTMAX:Quack_Jamef_Model_Request_Time_Response_Result:private] => 
            [CDTMIN:Quack_Jamef_Model_Request_Time_Response_Result:private] => 
            [MSGERRO:Quack_Jamef_Model_Request_Time_Response_Result:private] => CLIENTE NAO INFORMADO.;
        )

)
 in /var/www/vhosts/belabeleza-teste.app/html/app/Mage.php:580
Stack trace:
#0 /var/www/vhosts/belabeleza-teste.app/html/app/code/community/Quack/Jamef/Model/Carrier/Shipping.php(96): Mage::exception('Mage_Core', 'Quack_Jamef_Mod...')
#1 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Shipping/Model/Shipping.php(164): Quack_Jamef_Model_Carrier_Shipping->proccessAdditionalValidation(Object(Mage_Shipping_Model_Rate_Request))
#2 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Shipping/Model/Shipping.php(129): Mage_Shipping_Model_Shipping->collectCarrierRates('quack_jamef', Object(Mage_Shipping_Model_Rate_Request))
#3 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Sales/Model/Quote/Address.php(944): Mage_Shipping_Model_Shipping->collectRates(Object(Mage_Shipping_Model_Rate_Request))
#4 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Sales/Model/Quote/Address.php(875): Mage_Sales_Model_Quote_Address->requestShippingRates()
#5 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Sales/Model/Quote/Address/Total/Shipping.php(155): Mage_Sales_Model_Quote_Address->collectShippingRates()
#6 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Sales/Model/Quote/Address.php(1013): Mage_Sales_Model_Quote_Address_Total_Shipping->collect(Object(Mage_Sales_Model_Quote_Address))
#7 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Sales/Model/Quote.php(1331): Mage_Sales_Model_Quote_Address->collectTotals()
#8 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Checkout/Model/Cart.php(461): Mage_Sales_Model_Quote->collectTotals()
#9 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Checkout/controllers/CartController.php(161): Mage_Checkout_Model_Cart->save()
#10 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_CartController->indexAction()
#11 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#12 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#14 /var/www/vhosts/belabeleza-teste.app/html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#15 /var/www/vhosts/belabeleza-teste.app/html/index.php(83): Mage::run('', 'store')
#16 {main}

**Comment by rafaelpatro** [comment]
@tomjmacedo, acho q o _web service_ da Jamef não identificou corretamente sua cidade de origem. Tente remover o acento _Vitoria da Conquista_.

**Comment by rafaelpatro** [comment]
Se o erro persistir, tenta adicionar uma codificação UTF8 [nesta linha](https://github.com/rafaelpatro/Quack_Jamef/blob/master/app/code/community/Quack/Jamef/Model/Carrier/Abstract.php#L396).

Exemplo:
```php
->setMerchantCity(utf8_encode($this->getCity()))

**Comment by tomjmacedo** [comment]
Coloquei sem acento e também substituí o trecho de código mencionado, porém continua com o mesmo problema segue abaixo o novo log:

system.log:

2018-02-05T17:41:33+00:00 DEBUG (7): Quack_Jamef_Model_Carrier_Shipping::proccessAdditionalValidation
2018-02-05T17:41:33+00:00 DEBUG (7): Quack_Jamef_Model_Request_Time::requestShippingTime
2018-02-05T17:41:34+00:00 DEBUG (7): CLIENTE NAO INFORMADO.;

exception.log:

2018-02-05T17:41:34+00:00 ERR (3): 
Mage_Core_Exception: Quack_Jamef_Model_Request_Time_Response Object
(
    [JAMW0520_04RESULT:Quack_Jamef_Model_Request_Time_Response:private] => Quack_Jamef_Model_Request_Time_Response_Result Object
        (
            [CDTMAX:Quack_Jamef_Model_Request_Time_Response_Result:private] => 
            [CDTMIN:Quack_Jamef_Model_Request_Time_Response_Result:private] => 
            [MSGERRO:Quack_Jamef_Model_Request_Time_Response_Result:private] => CLIENTE NAO INFORMADO.;
        )

)
 in /var/www/vhosts/belabeleza-teste.app/html/app/Mage.php:580
Stack trace:
#0 /var/www/vhosts/belabeleza-teste.app/html/app/code/community/Quack/Jamef/Model/Carrier/Shipping.php(96): Mage::exception('Mage_Core', 'Quack_Jamef_Mod...')
#1 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Shipping/Model/Shipping.php(164): Quack_Jamef_Model_Carrier_Shipping->proccessAdditionalValidation(Object(Mage_Shipping_Model_Rate_Request))
#2 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Shipping/Model/Shipping.php(129): Mage_Shipping_Model_Shipping->collectCarrierRates('quack_jamef', Object(Mage_Shipping_Model_Rate_Request))
#3 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Sales/Model/Quote/Address.php(944): Mage_Shipping_Model_Shipping->collectRates(Object(Mage_Shipping_Model_Rate_Request))
#4 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Sales/Model/Quote/Address.php(875): Mage_Sales_Model_Quote_Address->requestShippingRates()
#5 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Sales/Model/Quote/Address/Total/Shipping.php(155): Mage_Sales_Model_Quote_Address->collectShippingRates()
#6 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Sales/Model/Quote/Address.php(1013): Mage_Sales_Model_Quote_Address_Total_Shipping->collect(Object(Mage_Sales_Model_Quote_Address))
#7 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Sales/Model/Quote.php(1331): Mage_Sales_Model_Quote_Address->collectTotals()
#8 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Checkout/Model/Cart.php(461): Mage_Sales_Model_Quote->collectTotals()
#9 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Checkout/controllers/CartController.php(161): Mage_Checkout_Model_Cart->save()
#10 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_CartController->indexAction()
#11 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#12 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /var/www/vhosts/belabeleza-teste.app/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#14 /var/www/vhosts/belabeleza-teste.app/html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#15 /var/www/vhosts/belabeleza-teste.app/html/index.php(83): Mage::run('', 'store')
#16 {main}

**Comment by rafaelpatro** [comment]
Desativou a cache do módulo? Recompilou?

**Comment by tomjmacedo** [comment]
Sim, porém persiste o problema.

**Comment by rafaelpatro** [comment]
Então, estou achando q é algum problema com sua região, mas teria q adicionar mais logs em mais alguns trechos pra averiguar.

Consegue fazer um teste configurando outra origem? Tente preencher os mesmos dados de origem [desse exemplo](https://github.com/rafaelpatro/Quack_Jamef#sistema--configura%C3%A7%C3%B5es--vendas-configura%C3%A7%C3%B5es-de-entrega), assim como a Filial de Coleta.

**Comment by tomjmacedo** [comment]
Coloquei as informações examente iguais ao do exemplo que você me passou tanto a origem do envio quanto as informações do módulo e segue abaixo o log do system.log:

system.log

2018-02-05T21:48:00+00:00 DEBUG (7): Quack_Jamef_Model_Carrier_Shipping::proccessAdditionalValidation

OBS: o exception.log está vázio.

**Comment by rafaelpatro** [comment]
Eita! Só deu isso no log?
Talvez o PHP ou Apache esteja lançando algum erro tb. Consegue dar uma olhada nisso tb?
Normalmente fica em

    /var/logs/apache2/error.log
    /var/logs/php_error.log

**Comment by williannagano** [comment]
Aqui tb to com mesmo problema. Eu to no php 5.6
2018-03-03T15:02:47+00:00 DEBUG (7): Quack_Jamef_Model_Request_Time::requestShippingTime
2018-03-03T15:02:47+00:00 DEBUG (7): CLIENTE N„O INFORMADO.;

**Comment by williannagano** [comment]
2018-03-03T14:52:08+00:00 DEBUG (7): Quack_Jamef_Model_Request_Time::requestShippingTime
2018-03-03T14:52:08+00:00 DEBUG (7): REGI„O DE DESTINO [VIRGINIA                                                    ]-[EX] N„O ENCONTRADA OU SEM FILIAL ASSOCIADA.;CLIENTE N„O INFORMADO.;

Mais cedo tinha dado isso. Mas não sei pq apareceu VIRGINIA aí. não tem nada relacionado ao cep que digitei.

**Comment by rafaelpatro** [comment]
Bom dia @williannagano 
Consegue colocar um log [nessa linha](https://github.com/rafaelpatro/Quack_Jamef/blob/master/app/code/community/Quack/Jamef/Model/Carrier/Shipping.php#L76)?

Coloca isso:

    Mage::log(print_r($timeRequest, true));

Em seguida faz uma cotação, e coloca aqui o _system.log_.

P.S. Será que o @tomjmacedo resolveu? Não postou mais nada.

**Comment by tomjmacedo** [comment]
Bom dia @rafaelpatro, ainda sem sucesso.

**Comment by rafaelpatro** [comment]
Aplica esse log que mencionei acima, e posta aqui o resultado.

**Comment by williannagano** [comment]
Eu percebi que no meu pc local tava funcionando de boa, aí subi meu banco daqui pro de produção. Agora ta funcionando de boa. E o banco que tava no produção, subi no local e não tava funcionando. Então algo que eu fiz depois que subi que deve ter dado algum erro. Mas único procedimento que fiz foi depois de ter instalado o jamef, eu instalei o módulo do correios, aí tive que apagar os atributos que eu tinha criado e assim utilizar os atributos que o módulo dos correios criou. Depois disso que deu pau. Mas a segunda vez q fiz esses mesmo passos de apagar o atributo, não deu pau.

**Comment by williannagano** [comment]
Respondendo a questão acima Rafael. Segue o log.
2018-03-06T16:26:30+00:00 DEBUG (7): Quack_Jamef_Model_Carrier_Shipping::proccessAdditionalValidation
2018-03-06T16:26:30+00:00 DEBUG (7): Quack_Jamef_Model_Request_Time Object
(
    [TIPTRA:Quack_Jamef_Model_Request_Time:private] => 
    [CNPJCPF:Quack_Jamef_Model_Request_Time:private] => 
    [MUNORI:Quack_Jamef_Model_Request_Time:private] => CURITIBA
    [ESTORI:Quack_Jamef_Model_Request_Time:private] => PR
    [MUNDES2:Quack_Jamef_Model_Request_Time:private] => 
    [ESTDES2:Quack_Jamef_Model_Request_Time:private] => 
    [CEPDES:Quack_Jamef_Model_Request_Time:private] => 86010065
    [CDATINI:Quack_Jamef_Model_Request_Time:private] => 06/03/2018
    [CHORINI:Quack_Jamef_Model_Request_Time:private] => 15:00
)

2018-03-06T16:26:30+00:00 DEBUG (7): Quack_Jamef_Model_Request_Time::requestShippingTime
2018-03-06T16:26:30+00:00 DEBUG (7): CLIENTE N„O INFORMADO.;

**Comment by smcpaiva** [comment]
Olá Rafael, boa tarde.
Estou com mesmo problema acima.
Fiz todos os testes, e contatei pessoal de integração da jamef.
Favor veja abaixo. Qualquer dica super bem-vinda:
//
Percebo o não preenchimento de campos obrigatórios durante a requisição, como: TIPTRA e CNPJCPF. O campo MUNORI (município de origem) foi passado com um caractere inválido: "?", provavelmente ocasionado devido à presença da acentuação "~". Sugiro utilizarem SAO PAULO, certamente com essas alterações o serviço funcionará normalmente.
//
2018-07-29T21:07:53+00:00 DEBUG (7): Quack_Jamef_Model_Carrier_Shipping::proccessAdditionalValidation
2018-07-29T21:07:53+00:00 DEBUG (7): Quack_Jamef_Model_Request_Time Object
(
[TIPTRA:Quack_Jamef_Model_Request_Time:private] =>
[CNPJCPF:Quack_Jamef_Model_Request_Time:private] =>
[MUNORI:Quack_Jamef_Model_Request_Time:private] => S?O PAULO
[ESTORI:Quack_Jamef_Model_Request_Time:private] => SP
[MUNDES2:Quack_Jamef_Model_Request_Time:private] =>
[ESTDES2:Quack_Jamef_Model_Request_Time:private] =>
[CEPDES:Quack_Jamef_Model_Request_Time:private] => 91010001
[CDATINI:Quack_Jamef_Model_Request_Time:private] => 01/08/2018
[CHORINI:Quack_Jamef_Model_Request_Time:private] => 12:00
)
2018-07-29T21:07:53+00:00 DEBUG (7): Quack_Jamef_Model_Request_Time::requestShippingTime
2018-07-29T21:07:53+00:00 DEBUG (7): loading from cache: id = QUACKJAMEF__91010001_1_01082018
2018-07-29T21:07:53+00:00 DEBUG (7): REGIâO DE ORIGEM [S?O PAULO ]-[SP] NâO ENCONTRADA OU SEM FILIAL ASSOCIADA.;CLIENTE NâO INFORMADO.;
//

Como disse fiz todas as correções sugeridas nesta issue, incluindo:
            ->setMerchantCity(utf8_encode($this->getCity()))

Muito obrigado.
Sérgio

**Comment by rafaelpatro** [comment]
Bom dia @smcpaiva
Realmente precisa preencher CNPJCPF e TIPTRA. Segue a origem destes campos...

* CNPJCPF:
_System > Configuration > General > Store Information > VAT Number_

* TIPTRA:
![image](https://user-images.githubusercontent.com/13813964/43458747-bdf4722e-94a1-11e8-95f9-16efc058ac02.png)

**Comment by smcpaiva** [comment]
Oi Rafael.
Obrigado pela tua atenção. 
O TIPTRA esta ativado com ambos, rodoviário e aéreo. Inseri o cnpj.
O erro é sempre o mesmo, mesmo alternando os CEPs de origem e destino.
//
2018-07-31T15:43:46+00:00 DEBUG (7): Quack_Jamef_Model_Request_Time Object
(
    [TIPTRA:Quack_Jamef_Model_Request_Time:private] =>
    [CNPJCPF:Quack_Jamef_Model_Request_Time:private] => 0197661140001XX
    [MUNORI:Quack_Jamef_Model_Request_Time:private] => S?O PAULO
    [ESTORI:Quack_Jamef_Model_Request_Time:private] => SP
    [MUNDES2:Quack_Jamef_Model_Request_Time:private] =>
    [ESTDES2:Quack_Jamef_Model_Request_Time:private] =>
    [CEPDES:Quack_Jamef_Model_Request_Time:private] => 91010001
    [CDATINI:Quack_Jamef_Model_Request_Time:private] => 03/08/2018
    [CHORINI:Quack_Jamef_Model_Request_Time:private] => 12:00
)

2018-07-31T15:43:46+00:00 DEBUG (7): Quack_Jamef_Model_Request_Time::requestShippingTime
2018-07-31T15:43:46+00:00 DEBUG (7): loading from cache: id = QUACKJAMEF_019766114000175_91010001_1_03082018
2018-07-31T15:43:46+00:00 DEBUG (7): REGIâO DE ORIGEM [S?O PAULO                                                   ]-[SP] NâO ENCONTRADA OU SEM FILIAL ASSOCIADA.;

Qualquer dica é bem vinda. Obrigado.

**Comment by rafaelpatro** [comment]
Altera as _Configurações de Entrega_, onde está cadastrado o endereço da loja. Tenta colocar o município sem acento.

**Comment by smcpaiva** [comment]
Sim, funcionou Rafael. Muito obrigado!! :)

**Comment by smcpaiva** [comment]
Oi Rafael,
Última.
O valor que esta sendo calculado para o módulo está muito alto.
Um envio local, mesma cidade, está saído por R$ 307, sendo que o cliente possui contrato com a Jamef, e simulando os mesmos dados, no site da jamef, fica em torno de 70.
Em contato com a jamef informaram que geralmente o que costuma causar divergências em valores de Frete são as medidas do Produto e peso. Mas aparentemente isto esta ok, e funcionando em outras formas de entrega, como jdlog e correios.
Favor veja o log. Talvez você saiba o que pode ser. Obrigado!



2018-08-15T17:04:04+00:00 DEBUG (7): Quack_Jamef_Model_Carrier_Shipping::collectRates
2018-08-15T17:04:04+00:00 DEBUG (7): Quack_Jamef_Model_Request_Price::requestShippingCost
2018-08-15T17:04:08+00:00 DEBUG (7): Quack_Jamef_Model_Request_Price_Response::getShippingCost
2018-08-15T17:04:08+00:00 DEBUG (7): Quack_Jamef_Model_Request_Price_Response Object
(
    [JAMW0520_05RESULT:Quack_Jamef_Model_Request_Price_Response:private] => Quack_Jamef_Model_Request_Price_Response_Result Object
        (
            [VALFRE:Quack_Jamef_Model_Request_Price_Response_Result:private] => Quack_Jamef_Model_Request_Price_Response_Result_Shipping Object
                (
                    [AVALFRE:Quack_Jamef_Model_Request_Price_Response_Result_Shipping:private] => Array
                        (
                            [0] => Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate Object
                                (
                                    [COMPONENTE:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => [01]-Pedagio
                                    [IMPOSTO:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 1.11409091
                                    [TOTAL:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 9.28409091
                                    [VALOR:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 8.17
                                )

                            [1] => Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate Object
                                (
                                    [COMPONENTE:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => [03]-GRIS
                                    [IMPOSTO:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 1.78636364
                                    [TOTAL:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 14.88636364
                                    [VALOR:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 13.1
                                )

                            [2] => Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate Object
                                (
                                    [COMPONENTE:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => [04]-TAS
                                    [IMPOSTO:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 0.88772727
                                    [TOTAL:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 7.39772727
                                    [VALOR:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 6.51
                                )

                            [3] => Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate Object
                                (
                                    [COMPONENTE:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => [05]-Taxa (ate 100kg)
                                    [IMPOSTO:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 14.18454545
                                    [TOTAL:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 118.20454545
                                    [VALOR:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 104.02
                                )

                            [4] => Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate Object
                                (
                                    [COMPONENTE:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => [06]-Frete Peso (FM)
                                    [IMPOSTO:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 12.10876364
                                    [TOTAL:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 100.90636364
                                    [VALOR:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 88.7976
                                )

                            [5] => Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate Object
                                (
                                    [COMPONENTE:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => [07]-Frete Valor
                                    [IMPOSTO:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 1.78636364
                                    [TOTAL:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 14.88636364
                                    [VALOR:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 13.1
                                )

                            [6] => Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate Object
                                (
                                    [COMPONENTE:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => [10]-TRT
                                    [IMPOSTO:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 4.92545455
                                    [TOTAL:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 41.04545455
                                    [VALOR:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 36.12
                                )

                            [7] => Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate Object
                                (
                                    [COMPONENTE:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => [23]-Frete Peso (FP)
                                    [IMPOSTO:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 0
                                    [TOTAL:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 0
                                    [VALOR:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 0
                                )

                            [8] => Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate Object
                                (
                                    [COMPONENTE:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => [24]-Taxa (acima 100kg)
                                    [IMPOSTO:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 0
                                    [TOTAL:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 0
                                    [VALOR:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 0
                                )

                            [9] => Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate Object
                                (
                                    [COMPONENTE:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => TF-TOTAL DO FRETE
                                    [IMPOSTO:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 36.79
                                    [TOTAL:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 306.61
                                    [VALOR:Quack_Jamef_Model_Request_Price_Response_Result_Shipping_Rate:private] => 269.82
                                )

                        )

                )

            [MSGERRO:Quack_Jamef_Model_Request_Price_Response_Result:private] => Ok - Calculo executado na filial [ POA ] cFilAnt : [05] Cliente Destinatario [  ]
        )

)

**Comment by rafaelpatro** [comment]
@smcpaiva, reparei que o cálculo está sendo enviado para a filial de Porto Alegre. Está correto isso? Qual sua localidade?

Pode enviar um print da tela de configurações do módulo?

**Comment by smcpaiva** [comment]
Oi Rafael, segue a tela. 
Testei diferentes filiais, porto alegre e são paulo.
![tela-jamef](https://user-images.githubusercontent.com/22639012/44177904-41a37400-a0c6-11e8-8e57-c1ddebaf3730.png)

Fiz uma simulação pelo site da Jamef (com os dados da empresa), utilizando as informações do mesmo produto, ficando em R$ 72,42. 
Neste caso o produto simulado tem valor de 119,90, peso 26,00 altura 0,10 comprimento 0,70 largura 0,40
Nisto não sei como é realizado o cálculo de peso cubado pelo módulo e site magento, que seria: Quantidade x Altura x Largura x Comprimento x Valor determinado na negociação (sem um valor especial seria 300).

De alguma forma a plataforma pode não estar calculando corretamente a cubagem na hora de informar para a Jamef.

Envie meu teste feito SOAP UI para o Suporte da plataforma:

Requisição:

<tot:JAMW0520_05>
         <tot:TIPTRA>1</tot:TIPTRA>
         <tot:CNPJCPF>1976611400017X</tot:CNPJCPF>
         <tot:MUNORI>SAO PAULO</tot:MUNORI>
         <tot:ESTORI>SP</tot:ESTORI>
         
         <tot:MUNDES2>?</tot:MUNDES2>
         
         <tot:ESTDES2>?</tot:ESTDES2>
         <tot:SEGPROD>000004</tot:SEGPROD>
         <tot:QTDVOL>1</tot:QTDVOL>
         <tot:PESO>26</tot:PESO>
         <tot:VALMER>119.90</tot:VALMER>
         <tot:METRO3>0.028</tot:METRO3>
         <tot:CNPJDES>?</tot:CNPJDES>
         
         <tot:FILCOT>07</tot:FILCOT>
         
         <tot:CEPDES>06220010</tot:CEPDES>
         
         <tot:CONTRIB>?</tot:CONTRIB>
      </tot:JAMW0520_05>

Resposta:


<AVALFRE>
                  <COMPONENTE>TF-TOTAL DO FRETE</COMPONENTE>
                  <IMPOSTO>8.69000000</IMPOSTO>
                  <TOTAL>72.42000000</TOTAL>
                  <VALOR>63.73000000</VALOR>
               </AVALFRE>

**Comment by rafaelpatro** [comment]
@smcpaiva, altera a opção de _Aplicar Empacotamento_ para _Por Pedido_.
E altera o campo _Tipo de Pacote Solicitado_ para _Dividir de Igual Peso (uma solicitação)_.
E certifique que as medidas dos produtos estejam em cm, e o peso em kg.

p.s.: sugiro manter a filial de SP para poder comparar com seu teste Soap. Usar outra filial pode mudar o valor da cotação.

**Comment by rafaelpatro** [comment]
Ahhh e altera o campo _Peso Máximo do Pacote_ para 30 kg ou mais.

**Comment by smcpaiva** [comment]
Beleza Rafael. No nosso caso o cnpj errado também não ajudou muito :/ Muito obrigado por sua atenção!
